CONTRACTIONS: dict[str, str] = {
    "ain't": "am not",
    "aren't": "are not",
    "can't": "cannot",
    "couldn't": "could not",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",
    "hadn't": "had not",
    "hasn't": "has not",
    "haven't": "have not",
    "he'd": "he would",
    "he'll": "he will",
    "he's": "he is",
    "i'd": "I would",
    "i'll": "I will",
    "i'm": "I am",
    "i've": "I have",
    "isn't": "is not",
    "it'd": "it would",
    "it'll": "it will",
    "it's": "it is",
    "let's": "let us",
    "mustn't": "must not",
    "shan't": "shall not",
    "she'd": "she would",
    "she'll": "she will",
    "she's": "she is",
    "shouldn't": "should not",
    "that's": "that is",
    "there's": "there is",
    "they'd": "they would",
    "they'll": "they will",
    "they're": "they are",
    "they've": "they have",
    "wasn't": "was not",
    "we'd": "we would",
    "we'll": "we will",
    "we're": "we are",
    "we've": "we have",
    "weren't": "were not",
    "what's": "what is",
    "where's": "where is",
    "who's": "who is",
    "won't": "will not",
    "wouldn't": "would not",
    "you'd": "you would",
    "you'll": "you will",
    "you're": "you are",
    "you've": "you have",
}

FIXED_FORM_RELATIONS: dict[str, tuple[str, str, str]] = {
    "am": ("be", "first_person_singular_of", "first-person singular of be"),
    "are": ("be", "present_plural_or_second_person_of", "present plural or second-person form of be"),
    "is": ("be", "third_person_singular_of", "third-person singular of be"),
    "was": ("be", "past_tense_singular_of", "past singular form of be"),
    "were": ("be", "past_tense_plural_of", "past plural or subjunctive form of be"),
    "been": ("be", "past_participle_of", "past participle of be"),
    "being": ("be", "present_participle_of", "present participle of be"),
    "does": ("do", "third_person_singular_of", "third-person singular of do"),
    "did": ("do", "past_tense_of", "past tense of do"),
    "done": ("do", "past_participle_of", "past participle of do"),
    "doing": ("do", "present_participle_of", "present participle of do"),
    "has": ("have", "third_person_singular_of", "third-person singular of have"),
    "had": ("have", "past_tense_of", "past tense of have"),
    "having": ("have", "present_participle_of", "present participle of have"),
}
