/**
 * This is the main build configuration file for the Android application module.
 * It defines plugins, Android-specific settings, and dependencies.
 */
plugins {
    // Standard Android application plugin
    alias(libs.plugins.android.application)
    // Jetpack Compose plugin for Kotlin
    alias(libs.plugins.kotlin.compose)
    // Kotlin Serialization plugin
    alias(libs.plugins.kotlin.serialization)
}

android {
    // Unique identifier for the R class and other generated code
    namespace = "com.siyehua.egnlishstudy"
    
    // SDK version used to compile the application
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        // Unique ID for the app on the Google Play Store
        applicationId = "com.siyehua.egnlishstudy"
        
        // Minimum Android version required to run the app (Android 10)
        minSdk = 29
        
        // Target Android version for runtime behavior optimizations
        targetSdk = 36
        
        // Internal version number used for updates
        versionCode = 2
        
        // Human-readable version string
        versionName = "2.0"

        // Runner for instrumentation tests
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // 用 debug 签名，方便直接安装测试
            signingConfig = signingConfigs.getByName("debug")
            // Configuration for release builds
            optimization {
                // R8 裁剪：不开启会把 Compose/Ktor/图标库全量打入（APK 47MB）
                enable = true
            }
        }
    }
    
    compileOptions {
        // Java version compatibility for the source code and generated bytecode
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    
    buildFeatures {
        // Enable Jetpack Compose support
        compose = true
        buildConfig = true
    }

}

dependencies {
    // Import the Compose Bill of Materials (BOM) to manage library versions
    implementation(platform(libs.androidx.compose.bom))
    
    // Core Android and Compose dependencies
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material.icons.extended)
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    
    // Networking
    implementation(libs.ktor.client.core)
    implementation(libs.ktor.client.okhttp)
    implementation(libs.ktor.client.content.negotiation)
    implementation(libs.ktor.serialization.kotlinx.json)
    implementation(libs.kotlinx.serialization.json)

    // Media notification (MediaStyle + MediaSessionCompat)
    implementation("androidx.media:media:1.7.0")
    
    // RSS Parsing
    implementation(libs.rss.parser)
    
    // Unit testing dependency
    testImplementation(libs.junit)
    
    // Instrumented testing dependencies
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.junit)
    
    // Debug-only dependencies for Compose tooling and testing
    debugImplementation(libs.androidx.compose.ui.test.manifest)
    debugImplementation(libs.androidx.compose.ui.tooling)
}
